# fly.toml app configuration file generated for flickr-service on 2023-10-10T23:30:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flickr-service"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT=3000
  REQUESTS_PER_MINUTE=500
  FLICKR_BASE_URL="https://api.flickr.com/services/rest"
  ALLOWED_REQUEST_ORIGIN_URLS=["https://www.floydkretschmar.com", "https://www.floydkretschmar.de", "https://floydkretschmar.com", "https://floydkretschmar.de"]